type User {
  name: String!
}

type Comment {
  id: Int!
  content: String!
  user: User!
}

type Post {
  id: Int!
  title: String!
  content: String!
  comments: [Comment!]!
}

type Query {
  posts: [Post!]!
}
